CREATE TABLE [dbo].[Produto] (
    ID INT IDENTITY (1, 1) NOT NULL,
    NOME VARCHAR (MAX) NOT NULL,
    DESCRICAO NVARCHAR (MAX) NOT NULL,
    CATEGORIA VARCHAR (MAX) NOT NULL,
    ESTOQUE INT NOT NULL,
    PRECO DOUBLE PRECISION NOT NULL,
    IMAGEM VARBINARY (MAX) NULL,
    TAMANHO VARCHAR (MAX) NULL,
    COR VARCHAR (MAX) NULL,
    DATAENTRADA DATE NULL,
    CONSTRAINT PK_Produto PRIMARY KEY (ID)
);

CREATE TABLE Endereco(
    ID INT IDENTITY(1,1) NOT NULL,
    LOGRADOURO VARCHAR(MAX) NOT NULL,
    COMPLEMENTO VARCHAR(MAX) NOT NULL,
    BAIRRO VARCHAR(MAX) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    CIDADE VARCHAR(MAX) NOT NULL,
    ESTADO VARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_Endereco PRIMARY KEY (ID)
);

CREATE TABLE Funcionario(
    ID INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(MAX) NOT NULL,
    SOBRENOME VARCHAR(MAX) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    RG VARCHAR(9) NULL,
    EMAIL VARCHAR(MAX) NOT NULL,
    TELEFONE VARCHAR(11) NULL,
    CELULAR VARCHAR(11) NULL,
    ENDERECOID INT NULL,
    CONSTRAINT PK_Funcionario PRIMARY KEY (ID),
    CONSTRAINT FK_Endereco FOREIGN KEY (ENDERECOID) REFERENCES Endereco (ID)
);

CREATE TABLE Transportadora(
    ID INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(MAX) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    ENTREGA DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_Transportadora PRIMARY KEY (ID)
);

CREATE TABLE Cliente(
    ID INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(MAX) NOT NULL,
    SOBRENOME VARCHAR(MAX) NOT NULL,
    TELEFONE VARCHAR(11) NULL,
    CPF VARCHAR(11) NOT NULL,
    SEXO VARCHAR(MAX) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    ENDERECOID INT NULL,
    CONSTRAINT PK_Cliente PRIMARY KEY (ID),
    CONSTRAINT FK_EnderecoC FOREIGN KEY (ENDERECOID) REFERENCES Endereco (ID)
);

CREATE TABLE Venda(
    ID INT IDENTITY(1,1) NOT NULL,
    NUMERO INT NOT NULL,
    CLIENTEID INT NOT NULL,
    DATACOMPRA DATE NOT NULL,
    TRANSPORTADORAID INT NOT NULL,
    ENTREGA INT NOT NULL,
    TOTALCOMPRA DOUBLE PRECISION NOT NULL,
    ESTADOATUAL VARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_Venda PRIMARY KEY (ID),
    CONSTRAINT FK_Cliente FOREIGN KEY (CLIENTEID) REFERENCES Cliente (ID),
    CONSTRAINT FK_Transportadora FOREIGN KEY (TRANSPORTADORAID) REFERENCES Transportadora (ID),
    CONSTRAINT FK_EnderecoV FOREIGN KEY (ENTREGA) REFERENCES Endereco (ID)
);

CREATE TABLE ItemVenda(
    VENDAID INT NOT NULL,
    PRODUTOID INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    CONSTRAINT PK_ItemVenda PRIMARY KEY (VENDAID, PRODUTOID),
    CONSTRAINT FK_Venda FOREIGN KEY (VENDAID) REFERENCES Venda (ID),
    CONSTRAINT FK_Produto FOREIGN KEY (PRODUTOID) REFERENCES Produto (ID)
);